---
title: regexed 🗯️
description: Regular Expressions Puzzles
author: Daniel James
timezone: America/Los_Angeles
email: daniel@thzinc.com
url: https://regexed.com
markdown: kramdown
collections:
  puzzles:
    output: true
  spoilers:
    output: true
defaults:
  - scope:
      path: ""
      type: "puzzles"
    values:
      layout: "puzzle"
      permalink: /puzzles/:name
  - scope:
      path: ""
      type: "spoilers"
    values:
      layout: "puzzle"
      permalink: /spoilers/:name
      sitemap: false
feed:
  collections:
    - puzzles
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
exclude:
  - .jekyll-cache/
  - "**/node_modules"
  - bin/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - puzzle/
